import Head from 'next/head'
import styles from '../styles/Home.module.css'
import DataContext from '../context/DataContext'
import { useContext, useEffect } from 'react'
import { RecipiesList } from '../components/recipiesList'
import data1 from "../data/data";

export default function Home() {

  // const data1 = data;
  const data = useContext(DataContext)
  useEffect(()=>{
    localStorage.setItem("item", JSON.stringify(data1));
  }, [])
 

  return (
    <div className={styles.container}>     
      <Head>
      <title>👨‍🍳CookChef</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>        
       
          {data.results.map(index=>{
            return <RecipiesList dish = {index}/>
          })}
          
       
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
