import Head from 'next/head'
import styles from '../styles/Home.module.css'
// import Image from 'next/image'
// import Contact from './contact'

export default function Home() {
  return (
    <div className={styles.container}>
     
      <Head>
      <title>👨‍🍳CookChef</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <Contact/> */}
        
        <div>Hare Krishna</div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
