import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from "next/link";
import DataContext from '../context/DataContext'
import { useRouter } from 'next/dist/client/router';
import { useContext, useEffect } from 'react'
import { RecipiesList } from '../components/recipiesList'
import data1 from "../data/data";
import { Button } from '@mui/material';
import { useAuth } from '../context/AuthContext'
import { Router } from '@mui/icons-material';

export default function Home() {

  // const data1 = data;
  const { currentUser } = useAuth();
  const data = useContext(DataContext)
  const router = useRouter()
  useEffect(()=>{
    localStorage.setItem("item", JSON.stringify(data1));
  }, [])
 

  return (
    <div className={styles.container}>     
      <Head>
      <title>👨‍🍳Aapni-Rasoi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>        
       
       <div className={styles.banner}>
        <h2 className={styles.h2}>Food is not just eating energy,Its an EXPERIENCE!!!</h2>

        {!currentUser && <div className = {styles.s1}>
        <Button className={styles.btn} variant="contained" onClick={()=>{router.push('/signin')}}>Sign In</Button>

          </div>}

       </div>

       <h1 className={styles.h1}>Our Famous Recipies</h1><br />

          {data.results.map(index=>{
            return <RecipiesList dish = {index}/>
          })}
          
       
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
